name: Playwright Tests on Chrome

on:
  push:
    branches: [main]

jobs:
  playwright-tests:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: Install Node.js
      uses: actions/setup-node@v3
      with:
        node-version: '18.x'
    - name: Install Playwright
      run: npm install -g playwright
    - name: Install Playwright browsers
      run: npx playwright install
    - name: Verify Playwright installation
      run: npx playwright --version
    - name: Run Playwright tests
      run: npx playwright test
